const defaultTheme = require('tailwindcss/defaultTheme');

const config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        'nav': '1280px', // Navigation breakpoint for menu display
        'nav-compact': '1280px', // Compact menu start
        'nav-full': '1440px', // Full menu start (was xxl)
        'xxl': '1440px', // Custom breakpoint for 1440px
      },
      // 정리된 색상 시스템 (UI/UX 분석 기반)
      colors: {
        // === 브랜드 컬러 (Primary) ===
        'primary': '#2563EB', // 메인 블루 (헤더, 주요 버튼, 브랜딩)
        'primary-dark': '#1D4ED8', // 호버 상태용 어두운 블루
        'primary-light': '#3B82F6', // 연한 블루 (배경, 강조)

        // === 배경 컬러 ===
        'background-main': '#FFFFFF', // 메인 배경 (순백)
        'background-section': '#F8FAFC', // 섹션/카드 배경 (밝은 회색)

        // === 확장된 액센트 컬러 ===
        'accent-blue': '#2563EB', // 메인 블루 (정보, 링크)
        'accent-green': '#059669', // 성공, 성장 (보조 컬러)
        'accent-green-light': '#10B981', // 연한 그린 (강조용)
        'accent-purple': '#7C3AED', // 창의성, 혁신 (보조)
        'accent-yellow': '#F59E0B', // 강조, 하이라이트 (보조)
        'accent-teal': '#0D9488', // 시원한 틸 (보조)

        // === 텍스트 컬러 ===
        'text-primary': '#424242', // 주요 텍스트 (진한 회색)
        'text-secondary': '#757575', // 보조 텍스트 (중간 회색)
        'text-on-primary': '#FFFFFF', // Primary 색상 위의 텍스트 (화이트)

        // === UI 컬러 ===
        'border-light': '#E2E8F0', // 경계선 (연한 회색)
        'border-primary': '#2563EB', // Primary 경계선

        // === 상태 컬러 ===
        'success': '#059669', // 성공 상태 (그린)
        'warning': '#F59E0B', // 경고 상태 (오렌지)
        'error': '#EF4444', // 오류 상태 (빨강)

        // === 확장된 중성 컬러 팔레트 ===
        'gray-50': '#F8FAFC',
        'gray-100': '#F1F5F9', 
        'gray-200': '#E2E8F0',
        'gray-300': '#CBD5E1',
        'gray-400': '#94A3B8',
        'gray-500': '#64748B',
        'gray-600': '#475569',
        'gray-700': '#334155',
        'gray-800': '#1E293B',
        'gray-900': '#0F172A',

        // === 외부 서비스 브랜드 컬러 ===
        'kakao': '#FEE500', // 카카오톡 옐로우
        'naver-green': '#03C75A', // 네이버 그린
        'naver-green-dark': '#028F48', // 네이버 호버 상태용 딥 그린
      },
      fontFamily: {
        // Use CSS variables generated by @next/font
        sans: ['var(--font-gmarket-sans)', 'var(--font-noto-sans-kr)', ...defaultTheme.fontFamily.sans], // Use CSS variables from next/font
        // gong: ['var(--font-gong)', ...defaultTheme.fontFamily.sans], // Removed GongGothic
      },
      
      // 체계적 타이포그래피 토큰 정의
      fontSize: {
        // 기존 Tailwind 크기 유지하면서 확장
        ...defaultTheme.fontSize,
        
        // === 제목 레벨 (반응형 + 가독성 최적화) ===
        'heading-1': ['2.75rem', {
          lineHeight: '1.2',
          letterSpacing: '-0.02em',
          '@screen md': {
            fontSize: '3.5rem',
            lineHeight: '1.2'
          }
        }], // 44px → 56px (h1) - 시각적 위계 강화

        'heading-2': ['2rem', {
          lineHeight: '1.3',
          letterSpacing: '-0.01em',
          '@screen md': {
            fontSize: '2.5rem',
            lineHeight: '1.3'
          }
        }], // 32px → 40px (h2) - 섹션 제목

        'heading-3': ['1.5rem', {
          lineHeight: '1.4',
          letterSpacing: '-0.01em',
          '@screen md': {
            fontSize: '1.75rem',
            lineHeight: '1.4'
          }
        }], // 24px → 28px (h3) - 카드 제목
        
        'heading-4': ['1.25rem', { 
          lineHeight: '1.75rem', 
          letterSpacing: '-0.025em',
          '@screen md': {
            fontSize: '1.375rem',
            lineHeight: '1.875rem'
          }
        }], // 20px → 22px (h4)
        
        // === 본문 레벨 (한글 최적화) ===
        'body-large': ['1.125rem', {
          lineHeight: '1.75',
          letterSpacing: '0em'
        }], // 18px (강조 본문)

        'body-base': ['1rem', {
          lineHeight: '1.75',
          letterSpacing: '0em'
        }], // 16px (기본 본문) - 한글 최적 line-height

        'body-small': ['0.875rem', {
          lineHeight: '1.7',
          letterSpacing: '0em'
        }], // 14px (보조 본문)
        
        'caption': ['0.75rem', { 
          lineHeight: '1.125rem',
          letterSpacing: '0.025em'
        }], // 12px (캡션, 라벨)
        
        // === 특별 용도 ===
        'display': ['3rem', { 
          lineHeight: '3.5rem', 
          letterSpacing: '-0.05em',
          '@screen md': {
            fontSize: '4rem',
            lineHeight: '4.5rem'
          }
        }], // 48px → 64px (히어로 제목)
      },
      // Enhanced shadow system for better depth
      boxShadow: {
        'xs': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        'sm': '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
        'md': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'xl': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        'inner': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        'none': 'none',
        // Enhanced card shadows
        'card': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'card-hover': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'card-lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'card-lg-hover': '0 25px 50px -12px rgba(0, 0, 0, 0.25), 0 20px 25px -5px rgba(0, 0, 0, 0.1)',
        // Neutral shadows for primary elements (removed colored shadows)
        'primary': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'primary-lg': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        // Enhanced gradient backgrounds
        'gradient-primary': 'linear-gradient(135deg, #2563EB 0%, #1D4ED8 100%)',
        'gradient-cool': 'linear-gradient(135deg, #2563EB 0%, #059669 100%)',
        'gradient-success': 'linear-gradient(135deg, #059669 0%, #10B981 100%)',
        'gradient-hero': 'linear-gradient(135deg, rgba(37, 99, 235, 0.8) 0%, rgba(5, 150, 105, 0.9) 100%)',
        'gradient-card': 'linear-gradient(145deg, rgba(255, 255, 255, 0.1) 0%, rgba(255, 255, 255, 0.05) 100%)',
      },
      // Custom animations for CTA enhancements
      keyframes: {
        'pulse-subtle': {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.02)', opacity: '0.95' }
        },
        'bounce-subtle': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-3px)' }
        },
        'glow': {
          '0%, 100%': { boxShadow: '0 0 5px rgba(37, 99, 235, 0.3)' },
          '50%': { boxShadow: '0 0 20px rgba(37, 99, 235, 0.6)' }
        }
      },
      animation: {
        'pulse-subtle': 'pulse-subtle 2.5s ease-in-out infinite',
        'bounce-subtle': 'bounce-subtle 2s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite'
      }
    },
  },
  plugins: [],
};

module.exports = config;
