const defaultTheme = require('tailwindcss/defaultTheme');

const config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        'nav': '1280px', // Navigation breakpoint for menu display
        'nav-compact': '1280px', // Compact menu start
        'nav-full': '1440px', // Full menu start (was xxl)
        'xxl': '1440px', // Custom breakpoint for 1440px
      },
      // 정리된 색상 시스템 (UI/UX 분석 기반)
      colors: {
        // === 브랜드 컬러 (Primary) ===
        'primary': '#E2690D', // 메인 오렌지 (헤더, 주요 버튼, 브랜딩)
        'primary-dark': '#CC5A0A', // 호버 상태용 어두운 오렌지
        'primary-light': '#F5944A', // 연한 오렌지 (배경, 강조)

        // === 배경 컬러 ===
        'background-main': '#FFFBF0', // 메인 배경 (아이보리)
        'background-section': '#FFFFFF', // 섹션/카드 배경 (화이트)

        // === 액센트 컬러 (2개로 축소) ===
        'accent-blue': '#4FC3F7', // 정보, 링크용 블루
        'accent-yellow': '#FFF176', // 강조, 하이라이트용 옐로우

        // === 텍스트 컬러 ===
        'text-primary': '#424242', // 주요 텍스트 (진한 회색)
        'text-secondary': '#757575', // 보조 텍스트 (중간 회색)
        'text-on-primary': '#FFFFFF', // Primary 색상 위의 텍스트 (화이트)

        // === UI 컬러 ===
        'border-light': '#E0E0E0', // 경계선 (연한 회색)
        'border-primary': '#E2690D', // Primary 경계선

        // === 상태 컬러 ===
        'success': '#22C55E', // 성공 상태 (더 선명한 초록)
        'warning': '#F59E0B', // 경고 상태 (더 선명한 오렌지)
        'error': '#EF4444', // 오류 상태 (더 선명한 빨강)

        // === 외부 서비스 브랜드 컬러 ===
        'kakao': '#FEE500', // 카카오톡 옐로우
        'naver-green': '#03C75A', // 네이버 그린
      },
      fontFamily: {
        // Use CSS variables generated by @next/font
        sans: ['var(--font-gmarket-sans)', 'var(--font-noto-sans-kr)', ...defaultTheme.fontFamily.sans], // Use CSS variables from next/font
        // gong: ['var(--font-gong)', ...defaultTheme.fontFamily.sans], // Removed GongGothic
      },
      
      // 체계적 타이포그래피 토큰 정의
      fontSize: {
        // 기존 Tailwind 크기 유지하면서 확장
        ...defaultTheme.fontSize,
        
        // === 제목 레벨 (반응형 + 가독성 최적화) ===
        'heading-1': ['2rem', { 
          lineHeight: '2.5rem', 
          letterSpacing: '-0.025em',
          '@screen md': {
            fontSize: '2.5rem',
            lineHeight: '3rem'
          }
        }], // 32px → 40px (h1)
        
        'heading-2': ['1.75rem', { 
          lineHeight: '2.25rem', 
          letterSpacing: '-0.025em',
          '@screen md': {
            fontSize: '2rem',
            lineHeight: '2.5rem'
          }
        }], // 28px → 32px (h2)
        
        'heading-3': ['1.5rem', { 
          lineHeight: '2rem', 
          letterSpacing: '-0.025em',
          '@screen md': {
            fontSize: '1.75rem',
            lineHeight: '2.25rem'
          }
        }], // 24px → 28px (h3)
        
        'heading-4': ['1.25rem', { 
          lineHeight: '1.75rem', 
          letterSpacing: '-0.025em',
          '@screen md': {
            fontSize: '1.375rem',
            lineHeight: '1.875rem'
          }
        }], // 20px → 22px (h4)
        
        // === 본문 레벨 (한글 최적화) ===
        'body-large': ['1.125rem', { 
          lineHeight: '1.75rem',
          letterSpacing: '0em'
        }], // 18px (강조 본문)
        
        'body-base': ['1rem', { 
          lineHeight: '1.625rem',
          letterSpacing: '0em'
        }], // 16px (기본 본문)
        
        'body-small': ['0.875rem', { 
          lineHeight: '1.375rem',
          letterSpacing: '0em'
        }], // 14px (보조 본문)
        
        'caption': ['0.75rem', { 
          lineHeight: '1.125rem',
          letterSpacing: '0.025em'
        }], // 12px (캡션, 라벨)
        
        // === 특별 용도 ===
        'display': ['3rem', { 
          lineHeight: '3.5rem', 
          letterSpacing: '-0.05em',
          '@screen md': {
            fontSize: '4rem',
            lineHeight: '4.5rem'
          }
        }], // 48px → 64px (히어로 제목)
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};

module.exports = config;